import type { Metadata } from "next";

import Head from "next/head";

import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";

import '@style/base.scss';

export const metadata: Metadata = {
  title: "ТитСтройСервис",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet" />
        <link rel="stylesheet" href="/fonts/style.css" />
      </head>
      <body>
        <Header />
        <div className="main">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
